### ISSUE TITLE
how about a npm package?

### ISSUE THREAD

**Issue by genzj** [sujan-s/fictoan#12]
Hello @sujan-s ,

The fictoan is a great light weighted framework! You really did a great job. BTW, doc and class-naming are also great, as good as monologue...

Why not publish it on the npm as a package? I think my developer will use fictoan if it can be installed quickly with one line.

Thanks a lot,
Jie

**Comment by sujan-s** [comment]
Hiya Jie!

Glad you like FICTOAN!

Yes, I've been mulling over that for a while now too. But I wanted to clean up a few things before putting it on npm to reach a wider audience. The next version is now in the works, with a better colour system, more UI elements and so on. I'll release an npm package with v3.0, hopefully in the coming weeks.

Again, thanks for showing interest, stay tuned for the updates!

Cheers!
